### ISSUE TITLE
feature request: file renaming

### ISSUE THREAD

**Issue by markomi** [apdavison/hbp_archive#2]
Would it be possible to implement a function that would enable renaming of files from a given container? Input parameters would be the current file name and the new file name.

I regularly have to download files from a container to my PC, then I rename files with a python script, then I replace container contents with the renamed file versions. However, I think it would be more elegant if I could preform renaming directly in the container without the download & re-upload procedure.

**Comment by markomi** [comment]
Thanks, that sounds good! I wonder how efficient the copy&move strategy will be for large objects. I guess we'll see, since openstack does not offer other options.

Would one then input two full object URLs? In that case one could perform rename & move at the same time. That'd be nice.

Also, it might be nice to throw an exception if an object with target URL already exists, and/or allow users to set a flag that would allow an overwrite (similar to what @appukuttan-shailesh and you have been discussing for download).

**Comment by appukuttan-shailesh** [comment]
Should we implement this as a part of `move` functionality? Along the lines of the Unix `mv` command.... i.e., if destination directory is not specified, then rename file in source directory.

**Comment by apdavison** [comment]
@markomi: I've released this as version 0.6.0, so `pip install -U` should give you the new version.

**Comment by appukuttan-shailesh** [comment]
It's interesting why you get that. For me:
```
In [1]: from hbp_archive import Container

In [2]: c = Container("<<container_name>>", "<<username>>")
Password: 

In [3]: c.list()
Out[3]: 
['HippoNetworkUnit/CA1_laminar_distribution_synapses.json',
 'HippoNetworkUnit/CA1_laminar_distribution_synapses_HBPmod.json',
 'README.txt',
 ...
 'morphounit/fs_morph_check_config.yml',
 'morphounit/fs_morph_check_cut_plane_config.json',
 'morphounit/fs_morpho_stats_NeuroM.json',
 'morphounit/msn_morph_check_config.yml',
 'morphounit/msn_morph_check_cut_plane_config.json']

In [4]: c.move("morphounit/msn_morph_check_cut_plane_config.json", "", overwrite=True)
Successfully moved the object

In [5]: c.list()
Out[5]: 
['HippoNetworkUnit/CA1_laminar_distribution_synapses.json',
 'HippoNetworkUnit/CA1_laminar_distribution_synapses_HBPmod.json',
 'README.txt',
...
 'morphounit/fs_morph_check_config.yml',
 'morphounit/fs_morph_check_cut_plane_config.json',
 'morphounit/fs_morpho_stats_NeuroM.json',
 'morphounit/msn_morph_check_config.yml',
 'msn_morph_check_cut_plane_config.json']

In [6]: c.move("msn_morph_check_cut_plane_config.json", "morphounit", overwrite=True)
Successfully moved the object

In [7]: c.list()
Out[7]: 
['HippoNetworkUnit/CA1_laminar_distribution_synapses.json',
 'HippoNetworkUnit/CA1_laminar_distribution_synapses_HBPmod.json',
 'README.txt',
...
 'morphounit/fs_morph_check_config.yml',
 'morphounit/fs_morph_check_cut_plane_config.json',
 'morphounit/fs_morpho_stats_NeuroM.json',
 'morphounit/msn_morph_check_config.yml',
 'morphounit/msn_morph_check_cut_plane_config.json']
```
@markomi : Could you check this again?

@apdavison : could you test the above example on the "sp6_validation_data" container using your account?

Note (unrelated to this issue): there is a problem with how `overwrite` is implemented as the error is thrown even when target file does not already exist! I will correct this asap.

**Comment by markomi** [comment]
@appukuttan-shailesh Thanks for suggesting me to try it again. I was not able to reproduce the problem this time. It works very nicely - thanks! I think you can close the issue. :)

Just a side note: I ran into problems when I tried to run the same code that works on Ubuntu (actually on a Linux subsystem on my Windows 10 laptop) on Windows directly. I might ask for Windows support at some point. But I am not sure if I really need it. If I decide to ask for it, I would open a separate issue. In case you are curious, here's a preview:

```
(_venv) C:\Users\mmarkovi\Code\Curation>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from hbp_archive import Container
>>> username = "bp000130"
>>> containername = "testSP1"
>>> filename = 'folder1p0/folder1p1/file1.txt'
>>> dest = 'folder1p0'
>>> dest2 = 'testSP1/folder1p0'
>>> newFilename = 'file1-new.txt'
>>> container = Container(containername, username)
Password:
>>> files = container.list()
>>> print("\n".join(map(str,files)))
'folder1p0'
'folder1p0/folder1p1'
'folder1p0/folder1p1/file1.txt'
'folder1p0/folder1p1/folder1p2'
>>> container.move(filename, dest, newFilename, overwrite = True)
Failed to move/rename the object with error: Object COPY failed: https://object.cscs.ch:443/v1/AUTH_63ea6845b1d34ad7a43c8158d9572867/testSP1/folder1p0/folder1p1/file1.txt 412ad7a43c8158d9572867/testSP1/folder1p0/folder1p1/file1.txt                                                        '
412 Precondition Failed  [first 60 chars of response] b'Destination header must be of the form <container name>/<
Failed to move/rename the object with error: Object COPY failed: https://object.cscs.ch:443/v1/AUTH_63ea6845b1d34ad7a43c8158d9572867/testSP1/folder1p0/folder1p1/file1.txt 404SP1/folder1p0/folder1p1/file1.txt 412 Precondition Failed  [first 60 chars of response] b'Destination header must be of the form <container name>/<obj'
>>> container.move(filename, dest2, newFilename, overwrite = True)
Failed to move/rename the object with error: Object COPY failed: https://object.cscs.ch:443/v1/AUTH_63ea6845b1d34ad7a43c8158d9572867/testSP1/folder1p0/folder1p1/file1.txt 404 Not Found  [first 60 chars of response] b'<html><h1>Not Found</h1><p>The resource could not be found.<'
>>> dest
'folder1p0'
>>> dest2
'testSP1/folder1p0'
>>> load_dest = container.download(dest)
>>> container.read(filename)
'abc'
>>>
```
